### ISSUE TITLE
More (and adjusted) fields

### ISSUE THREAD

**Issue by ericaltshuler** [lorenzotan/brokerV2#19]
1) need a total of four phone fields (work, cell, other and FAX)
2) need a total of two emails (primary and other)
3) change "Solicitation" to "Solicitation Period"
4) Can the phone numbers be formatted? Like now, you do 3105031966, can you make it look like (310) 503-1966?

**Comment by lorenzotan** [comment]
11ad706
added phone and email fields. these still need to be tested.

**Comment by lorenzotan** [comment]
updated labels and formatted phone numbers

84d92e271f9d73146e08366b63176c5231322fe1
