### ISSUE TITLE
LENDER FORM - checkboxes

### ISSUE THREAD

**Issue by ericaltshuler** [lorenzotan/brokerV2#31]
Can the check boxes easily be moved closer to the actual field? or even placed on the other side? As it is, the check boxes are closer to other field names than their own.

**Comment by ericaltshuler** [comment]
Also, then they move, it would be good if the fields are all on one line (if possible), for example Business Acquisitions is on two lines.

**Comment by lorenzotan** [comment]
Marking this as a duplicate. I will include the comments from here into the [other ticket](https://github.com/lorenzotan/brokerV2/issues/16).
