### ISSUE TITLE
BROKERS FORM AND LIST, CONTACTS FORM AND LIST

### ISSUE THREAD

**Issue by ericaltshuler** [lorenzotan/brokerV2#36]
Make a very simple Brokers Form and List and Contacts Form and List

FORM: For the brokers form, we can do more sophisticated stuff later, but for now, having the exact same form as the Lender Information would be fine. We can do the Lists of Lenders later. Same for Contacts.

LIST: Make the List much like the lenders has

ADMIN: Be able to  export the List. Make sure the name is different for the lenders, the brokers, and the contacts.

**Comment by lorenzotan** [comment]
1451e74

Created placeholder links in menu.

**Comment by lorenzotan** [comment]
[duplicate](https://github.com/lorenzotan/brokerV2/issues/6)
