### ISSUE TITLE
LENDER FORM - Changes

### ISSUE THREAD

**Issue by ericaltshuler** [lorenzotan/brokerV2#43]
- [x] 1) Add the field "Industrial" to both the Owner Occupied Real Estate and Investment Real Estate subforms
- [x] 2)  Add "SBA Express" in the SBA subform
- [x] 3) Add the boxes "Equipment" , "Working Capital", "Interest Only", Secured by Accts Receivable", "Secured by Inventory", in the BLOC subform
- [x] 4) Change the Title (not checkbox) from "Bridge Loan" to Miscellaneous Loans". Add "Commercial term Loans" , "USDA" and "Stated Income"  check boxes in the Miscellaneous Loans subform
- [x] 5) Add the checkbox "Franchises" in the qualifiers subform
- [x] 6) in the "property types, add the checkbox "Salon"
- [x] 7) In the Property types subform, change the checkbox "Marina" to "Marina/Slip"
- [x] 8) In the Property types subform, change the checkbox "Mobile Home" to "Mobile Home Park"
- [x] 9) In the Qualifiers subform, change "relationship" to "Relationship Pricing"
- [x] 10) In the HELOC subform, add "3rd Position"
- [x] 11) in the BLOC, add both "RE Secured" and "RE Unsecured" check-boxes
- [x] 12) Add "Investor" to the Construction Loan subform
- [ ] 13) If possible, add "12 Month", "18 months", 24 months" and "36 Months" to the RIGHT SIDE of the Miscellaneous Loans subform. I want to kind of separate the types from the durations. Let me know if this is a huge amount of work. If it is, then lets skip this part until we make it look more professional
- [x] 14) Add ITL to the SBA loan subform

**Comment by ericaltshuler** [comment]
15. Add "Mixed Use" to the property types

**Comment by ericaltshuler** [comment]
16. Add campground to property types
17. Add racetrack to property types

**Comment by lorenzotan** [comment]
9311903
Added new property types

**Comment by lorenzotan** [comment]
b2a53e2
adding more property types and qualifiers

**Comment by lorenzotan** [comment]
14ea1a5
adding fields to lender form
