### ISSUE TITLE
NEW MAJOR HEADER

### ISSUE THREAD

**Issue by ericaltshuler** [lorenzotan/brokerV2#49]
Add a new major header next to "Tools" called "Links". Add the following links to this page

American Association of Private Lenders --> https://aaplonline.com/directory
C-Loans --> https://www.c-loans.com/
Safe Harbor for Business --> https://safeharborforbusiness.com/
Scotsman Guide --> https://www.scotsmanguide.com/
South Bay Equity Lending --> http://www.southbayequitylending.com/
US Bank Locations --> https://www.usbanklocations.com

**Comment by ericaltshuler** [comment]
Investopedia --> https://www.investopedia.com

and order doesnt really matter, so alphabetical works as well as anything

**Comment by lorenzotan** [comment]
262da90
adding new links to nav
